# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || 'master' }}
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Android SDK
      run: ./android/travis_androidsdk.sh

    - name: Print versions
    run:
        java -version
        ./gradlew --version
        echo "ANDROID_HOME=$ANDROID_HOME"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
        find $ANDROID_HOME/ndk -maxdepth 2 -type d || true

    - name: Build with Gradle
      run: ./gradlew build   # или ./gradlew ciPublish, если нужно публиковать
      env:
        MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
        MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}